name: 'Okta Terraform'
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: 'debug with tmate'
        default: false
  push:
    paths:
      - "terraform-config/**"
      - "terraform-modules/**"
      - ".github/workflows/terraform.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "terraform-config/**"
      - "terraform-modules/**"
      - ".github/workflows/terraform.yaml"
jobs:
  Terraform-Plan:
    if: github.ref_name != github.event.repository.default_branch
    permissions: # Must change the job token permissions to use JWT auth
      contents: write
      id-token: write
      pull-requests: write
    concurrency:
      group:   ${{ github.workflow }}-${{ matrix.dir }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        dir: ["terraform-config/accounts","terraform-config/apps", "terraform-config/network"]
    uses: celo-org/reusable-workflows/.github/workflows/terraform.yaml@v3.0.0
    with:
      working-dir: ${{ matrix.dir }}
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-okta-live-config/providers/github-by-repos
      service-account: prod-terraform-clabs-okta@security-circle.iam.gserviceaccount.com 
      akeyless-api-gateway: https://api.gateway.akeyless.celo-networks-dev.org
      akeyless-github-access-id: p-kf9vjzruht6l
      token-format: "access_token"
      access-token-scopes: https://www.googleapis.com/auth/admin.directory.group.member, https://www.googleapis.com/auth/admin.directory.group
      runs-on: "['self-hosted', 'org', 'terraform']"
      environment: development
      debug-enabled: ${{ inputs.debug != '' && inputs.debug || false }}

  Terraform-Apply:
    if: github.ref_name == github.event.repository.default_branch
    permissions: # Must change the job token permissions to use JWT auth
      contents: read
      id-token: write
      pull-requests: write
    concurrency:
      group:   ${{ github.workflow }}-${{ matrix.dir }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        dir: ["terraform-config/accounts","terraform-config/apps", "terraform-config/network"]
    uses: celo-org/reusable-workflows/.github/workflows/terraform.yaml@v3.0.0
    with:
      working-dir: ${{ matrix.dir }}
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-okta-live-config/providers/github-by-repos
      service-account: prod-terraform-clabs-okta@security-circle.iam.gserviceaccount.com 
      akeyless-api-gateway: https://api.gateway.akeyless.celo-networks-dev.org
      akeyless-github-access-id: p-kf9vjzruht6l
      token-format: "access_token"
      access-token-scopes: https://www.googleapis.com/auth/admin.directory.group.member, https://www.googleapis.com/auth/admin.directory.group
      runs-on: "['self-hosted', 'org', 'terraform']"
      environment: production
      debug-enabled: ${{ inputs.debug != '' && inputs.debug || false }}
